# Generated by Django 5.0.6 on 2024-07-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(related_name='issues', to='webapp.type', verbose_name='Тип'),
        ),
    ]
